version: "3.7"
services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgres/data
    ports:
      - "5437:5432"
  
  api:
    depends_on:
      - db  # This makes sure the "db" service is started before the API service
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      JWT_SECRET: palmeiras
      DB_URL: "${DB_URL}"
      DB_DIALECT: ${DB_DIALECT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "3337:3337"

  app:
    depends_on:
      - db
      - api
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - REACT_APP_BASE_URL=http://0.0.0.0:3337
      - GENERATE_SOURCEMAP=false
    ports:
      - 3777:3000

volumes:
  db-data:
  api-data:
  app-data:
