version: "3.7"
services:
  db:
    image: postgis/postgis
    restart: always
    environment:      
      #POSTGRES_DB: forumDB
      #POSTGRES_USER: admin
      #POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  api:
    depends_on:
      - db  # This makes sure the "db" service is started before the API service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3333:3333"

volumes:
  db-data:
  api-data:
