version: "3.7"
services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

volumes:
  db-data:
